### ISSUE TITLE
[netboot] main.go: compile error

### ISSUE THREAD

**Issue by jenstopp** [systemboot/systemboot#109]
the change in #103 leads to error:
```
netboot/main.go:349:54: cannot use *userClass (type string) as type []byte in argument to dhcpv4.WithUserClass
```

**Comment by pmazzini** [comment]
@jensdrenhaus Are you using the latest version of the dhcp library?

`dhcpv4.WithUserClass` takes a string: https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/modifiers.go#L91

**Comment by jenstopp** [comment]
ok, got it. 
Are there plans to integrate that libs into systemboot? 
Why are some libs hosted in Andreas own repo?

**Comment by insomniacslk** [comment]
> Are there plans to integrate that libs into systemboot?

No, the netboot code belongs to the DHCP library, not to systemboot. I had the same conversation with @zaolin a few days ago.

> Why are some libs hosted in Andreas own repo?

because it's where the DHCP library was born :) we may move it under the coredhcp organization at some point in the future, but not until that project is mature and usable enough
